provide FrameDecoder with its own logger
odin-detector/odin-data pull request #251
Opened 2020-10-29 15:24 UTC by wnichols1

as agreed in meeting 29/10

2020-10-29 15:27 UTC, timcnicholls requested changes

2020-10-29 15:27 UTC, timcnicholls commented on frameReceiver/src/FrameDecoder.cpp
> +   logger_ = Logger::getLogger("FR.FrameDecoder");
This should be done in the member initialisation list to be consistent with the other classes, rather than in the body of the constructor.

2020-10-29 19:23 UTC, wnichols1 commented on frameReceiver/src/FrameDecoder.cpp
> +   logger_ = Logger::getLogger("FR.FrameDecoder");
ok done

2020-10-30 07:47 UTC, ajgdls commented
To smooth the way for the API change, is it worth overloading the init method to already have the version in place without the logger pointer?  I don't know if it is worth doing so I'll approve anyway.

2020-10-30 07:47 UTC, ajgdls approved these changes

2020-10-30 07:52 UTC, timcnicholls commented
> To smooth the way for the API change, is it worth overloading the init method to already have the version in place without the logger pointer? I don't know if it is worth doing so I'll approve anyway.

That's a good idea @ajgdls then decoder plugins can start to support the new API without a step change in compatibility.

@wnichols1 are you happy to add a further `init` method without the `LoggerPtr` argument?

2020-10-30 10:38 UTC, wnichols1 commented
ok done.

2020-10-30 11:12 UTC, GDYendell approved these changes

2020-10-30 13:34 UTC, timcnicholls approved these changes

2020-10-30 13:35 UTC, merged