Add an option for setting HDF5 file postfix.
odin-detector/odin-data pull request #292
Opened 2022-01-25 14:59 UTC by ajgdls

For a case where data is stored into file with geographical separation instead of round robin of frames it makes sense for the file names to be labelled with slightly different names and all retain the same numbering (e.g.):
file_A_000001.h5
file_B_000001.h5
This change allows the specification of a file postfix (_A or _B in the example above) placed before the automatic numbering.

2022-01-26 07:44 UTC, timcnicholls requested changes
No issues with the PR, although the `Acquisition::generate_filename()` method docstring could benefit from updating to mention the postfix also. 

I'l also like to suggest that we follow up on the long-standing request to make the fixed format file numbering optional too 😄

2022-01-26 09:27 UTC, ajgdls commented
This would be a good time to make that change!  Is it a boolean flag that you would like to be able to set (turn on or off numbering)?  Also I remember someone (maybe William) suggesting the file numbering should start from a configured number so we could have the files starting with index 0 instead of 1.  Shall I stick that in too?

2022-01-26 10:58 UTC, timcnicholls commented
> This would be a good time to make that change! Is it a boolean flag that you would like to be able to set (turn on or off numbering)? Also I remember someone (maybe William) suggesting the file numbering should start from a configured number so we could have the files starting with index 0 instead of 1. Shall I stick that in too?

I think having both ia boolean enable and a start index would be perfect thanks. We can make them default to the current behaviour (enabled/starting at 1) so it doesn't surprise anyone.

2022-03-02 16:48 UTC, ajgdls commented
There is now a starting index configuration parameter and a numbering on/off configuration parameter.  The defaults are for indexing to be 0 indexed (which really is the most used indexing) instead of 1 indexed, and for the numbers to be turned on by default.

2022-03-03 11:05 UTC, ajgdls commented
Yay finally I believe the tests are all passing, and I have implemented the additional config items for setting the starting file index and turning off file numbering.  @timcnicholls @GDYendell  I think this is now ready for review again.

2022-03-03 11:17 UTC, timcnicholls approved these changes

2022-03-08 11:02 UTC, GDYendell commented on frameProcessor/src/Acquisition.cpp
> +  if (!generated_filename.str().empty()){
Would it be better to have an else with a default name if the `configured_filename` and `acquisition_id` are both empty and then get rid of this check? I think this method should always return `<something>.h5`.

2022-03-16 16:00 UTC, ajgdls commented on frameProcessor/src/Acquisition.cpp
> +  if (!generated_filename.str().empty()){
I haven't changed the behaviour, the method specifically mentions returning an empty string if filename and acqID are not defined.
Later in the code (in start_acquisition method) the assigned variable from this return value is checked for empty string so I think this is doing what it was designed to do.

2022-03-16 16:22 UTC, GDYendell commented on frameProcessor/src/Acquisition.cpp
> +  if (!generated_filename.str().empty()){
Hmm, OK. Maybe it is how it is used in `get_file` that is wrong then: https://github.com/odin-detector/odin-data/blob/master/frameProcessor/src/Acquisition.cpp#L554

2022-05-16 10:48 UTC, ajgdls commented on frameProcessor/src/Acquisition.cpp
> +  if (!generated_filename.str().empty()){
@GDYendell , in the start_acquisition method if the filename is empty then the writer never starts running and so this `get_file` method would never be called I think:

```
  // Generate the filename
  filename_ = generate_filename(concurrent_rank_);

  if (filename_.empty()) {
    last_error_ = "Unable to start writing - no filename to write to";
    LOG4CXX_ERROR(logger_, last_error_);
    return false;
  }

```
Although it isn't the most elegant code it is functional and I don't think I want to change that behaviour as part of this PR.  Are you satisfied with that?  We could raise an issue to mention that this needs cleaning up?

2022-05-16 10:50 UTC, GDYendell commented on frameProcessor/src/Acquisition.cpp
> +  if (!generated_filename.str().empty()){
Sounds good to me

2022-05-16 10:54 UTC, ajgdls commented on frameProcessor/src/Acquisition.cpp
> +  if (!generated_filename.str().empty()){
OK then I'll merge this and raise an issue :+1:

2022-05-16 11:08 UTC, merged