Add TCP Receiver
odin-detector/odin-data pull request #339
Opened 2024-03-07 15:07 UTC by jsouter

Adds in the TCP rx thread required for merlin-detector.

2024-03-19 09:43 UTC, timcnicholls requested changes
Looks good! A few minor comments. It would be great if there was a dummy decoder plugin and integration test added for TCP receivers too 😉

2024-03-19 09:43 UTC, timcnicholls commented on cpp/frameReceiver/src/FrameReceiverTCPRxThread.cpp
> +    // Bind the socket to the specified port
This line (and the error message at line 82) refer to binding the socket - should both be changed to reflect fact that socket is connected (line 79)?

2024-03-19 09:43 UTC, timcnicholls commented on cpp/frameReceiver/src/FrameReceiverTCPRxThread.cpp
> +{
I think the socket be removed from the reactor and closed in the cleanup method to avoid dangling TCP connections in TIMED_WAIT states? See the ZMQ  RX thread implementation for an example.

2024-03-25 08:51 UTC, jsouter commented
Cheers Tim, I'll get to work on those changes

2024-05-09 10:52 UTC, jsouter commented
Having some trouble REGISTERing a second Dummy decoder, think it's an issue with the CMake in the FR test directory which has to link the APP_SOURCES cpp files to the executable, and the REGISTER macro doesn't work when it is called twice within a single translation unit(?)

2024-05-09 13:23 UTC, jsouter commented
Looking at this again, have made the minor changes to error messages mentioned above and added in a remove_socket call in the TCPRxThread's cleanup_specific_service. Had some issues with getting the build to work when registering a new Dummy decoder class but now I have a DummyTCPFrameDecoder somewhat resembling the Merlin frame decoder. Will set about working on the actual unit tests soon.

2024-07-15 14:44 UTC, jsouter commented
Okay, I removed the *Lib.cpp files from the glob in the CMakeLists.txt as discussed and removed the namespacing of the registrations. I will note that because of recent changes to master using Lambda functions, we may need to add in a set(CMAKE_CXX_STANDARD 11) call somewhere in the CMake, which is absent from this PR.

2024-07-19 08:23 UTC, timcnicholls approved these changes

2024-07-19 09:31 UTC, ajgdls approved these changes

2024-07-19 12:08 UTC, merged

2024-07-19 12:08 UTC, GDYendell commented
Thanks @jsouter!