Create FR and FP controllers inheriting from OdinController
odin-detector/odin-data pull request #362
Opened 2024-10-07 12:09 UTC by jsouter

Following discussion from https://github.com/odin-detector/odin-data/issues/346

Removes all logic relating to the frame processor flag from OdinDataController, and implements FR and FP specific logic in subclasses. If we do want to use the same controller for both the FP and FR adapter I have tested that it works okay with FastCS and it would be sufficient to delete the redundant (and now broken) frame_receiver_adapter.py

Also a small fix that renames a parameter in the Dummy decoders to class instead of name (as signals called "name" and "description" get excluded when the full ParameterTree is requested and can not be added to FastCS).

2024-10-07 12:18 UTC, jsouter commented on python/src/odin_data/control/odin_data_adapter.py
> +                "response": "OdinDataAdapter GET error: {}".format(param_error)
Realising this should probably get the class name instead if we're subclassing

2024-10-07 13:44 UTC, GDYendell commented on python/src/odin_data/control/odin_data_adapter.py
> +                "response": "OdinDataAdapter GET error: {}".format(param_error)
Agree. Let's see what we decide first.

2024-10-07 14:06 UTC, GDYendell commented
Alan's odin-control branch has been merged and deleted. I have update fastcs-dev to use odin-control main instead. If you rebase (and make sure to remove the commit to pin odin-control to a branch) it should fix the build here.

2024-10-08 07:36 UTC, jsouter commented
> Alan's odin-control branch has been merged and deleted. I have update fastcs-dev to use odin-control main instead. If you rebase (and make sure to remove the commit to pin odin-control to a branch) it should fix the build here.

Okay pushed that, seems to work as before after rebasing.

2024-10-11 15:39 UTC, ajgdls requested changes
Would it be possible to break out the FrameProcessorController into its own file (so basically one file for each class, named the same as the class but with underscore rather than camel case)?  I think it will make it clearer to see what is available if you are just looking around the directories.

2024-10-14 12:39 UTC, jsouter commented
> Would it be possible to break out the FrameProcessorController into its own file (so basically one file for each class, named the same as the class but with underscore rather than camel case)? I think it will make it clearer to see what is available if you are just looking around the directories.

Okay, just pushed that change

2024-10-14 13:56 UTC, GDYendell commented on python/src/odin_data/control/odin_data_adapter.py
> +                "response": "OdinDataAdapter GET error: {}".format(param_error)
OK so I think we change this to `self.__class__` now?

2024-10-14 13:57 UTC, GDYendell commented
Note this will break fastcs-odin when merged, it will need to have its config files updated.

2024-10-14 14:05 UTC, GDYendell commented
@jsouter could you squash the last 3 commits into one? I think we are good to merge.

2024-10-14 14:13 UTC, jsouter commented
> @jsouter could you squash the last 3 commits into one? I think we are good to merge.

Done!

2024-10-14 14:56 UTC, GDYendell approved these changes

2024-10-14 14:57 UTC, merged

2024-10-14 15:51 UTC, GDYendell commented
Uh, does this logic need to be moved somewhere else? https://github.com/odin-detector/odin-data/pull/362/files#diff-af879f9e3b965b6fe0832f413026c82c57dd5f10c0103d6c3a39723f68ff0cdfL41

2024-10-15 07:18 UTC, jsouter commented
Ah good point, it's possible, I had assumed this was covered by OdinDataController.process_config_changes. I will try and test if the decoder gets reloaded when it should.